RobotLocomotion/drake-blender

.bazelrc, .github/ci.bazelrc, .github/workflows/main.yml
Towards #3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/6)
=> Add CI infrastructure

BUILD.bazel, WORKSPACE.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/8)
=> Add missing public; fix lint

BUILD.bazel, README.md, server.py, server_test.py
My proposal is that we should merge this now, even though it lacks sufficient testing, comment clarity, etc. Loading of `*.blend` files probably doesn't work right either. After trying a few approaches though, I think it will be best to have a working prototype on the main branch, and then continue improving it from there.
---
Here's for forthcoming demo (#9) rendered using this code:
https://user-images.githubusercontent.com/17596505/230738201-847cced4-05ae-438b-bf66-8e469cb43f5e.mp4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)
=> Add server code, copied from TRI

BUILD.bazel, test/server_test.py
+@zachfang for review, please.  This will make #17 easier to review if we merge this then rebase that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/18)
=> Move server_test into a subdir

server.py, test/server_test.py
Toward #4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/21)
=> Reset blender env properly and add a consistency test

README.md
See preview here: https://github.com/jwnimmer-tri/drake-blender/tree/credits#credits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/27)
=> [doc] Add credits

server.py, test/server_test.py
+@zachfang for review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/31)
=> Add --bpy_settings_file option to server

README.md, WORKSPACE.bazel, examples/BUILD.bazel, examples/README.md, examples/ball_bin.py, examples/ball_bin.yaml, examples/test/ball_bin_test.py, examples/test/bpy_use_cycles.py
~\CC @zachfang FYI.  This was something I was playing with a few weeks ago.  I've rebased it now, but haven't tried re-running it.  I assume something is still broken.~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12)
=> Update ball_bin example to use a blend file

WORKSPACE.bazel, examples/ball_bin.py, examples/test/ball_bin_test.py, examples/test/bpy_use_cycles.py
The whitespace is to nudge Reviewable.
It will be reverted prior to merge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32)
=> Platform review of examples

examples/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/41)
=> [examples] Use OpenCV from pip (not Ubuntu)

BUILD.bazel, defs.bzl, examples/ball_bin.py, fix_lint.sh, pyproject.toml, requirements.txt, test/requirements.in, test/requirements.txt, test/server_test.py
Fix existing lint.
Towards https://github.com/RobotLocomotion/drake-blender/issues/25.
+@zachfang for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/46)
=> Add isort linting

README.md, fix_lint.sh, requirements_upgrade.sh
Amends #47.
+@zachfang for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/48)
=> [doc] Clarify maintainer script docs

BUILD.bazel, README.md, examples/BUILD.bazel, examples/requirements.in, requirements.in, test/requirements.in, tools/BUILD.bazel, tools/black_main.py, tools/defs.bzl, tools/fix_lint.sh, tools/isort_main.py, tools/pycodestyle_main.py, tools/requirements_upgrade.sh
This requires adding wrapped main functions, and that's enough new mass to push me to move our developer tools into a new sub-directory.
Closes #49.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50)
=> Add autofix suggestion when lint tools fail

examples/BUILD.bazel, examples/ball_bin.py, examples/test/ball_bin_test.py
Closes #42 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/58)
=> Add a video test in the example folder

LICENSE.TXT
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/98)
=> Bump license date to 2024

.github/workflows/main.yml, examples/test/ball_bin_test.py
Towards #95.
In the GitHub "Continuous Integration" details link, you can find a link to the download by unfolding the "Archive test outputs" step's log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/97)
=> [examples] Save test output for eyeball inspection

bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/109)
=> Upgrade bazelisk to latest release 1.25.0

test/server_test.py
CI has been seeing some flakes with the 1 second timeout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/115)
=> Give the test more time to shut down

.github/ci_setup.bash
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/117)
=> [ci] Add missing update to ci_setup

LICENSE.TXT, README.md, pyproject.toml
+@rpoyner-tri for review, please?
FYI @SeanCurtis-TRI @zachfang.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/118)
=> Prep for 0.2.1 release tag

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/120)
=> Bump version for post-0.2.1 development

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/124)
=> Disable renovate on actions/python-versions

.github/renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/126)
=> Revert "Disable renovate on actions/python-versions"

.github/workflows/main.yml, README.md, requirements.in, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/141)
=> Add --extra-index-url for older blender

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake-blender/150)
=> Bump version for post-0.3.0 development
